### ISSUE TITLE
when adding new host, "1007" related error message

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#37]
When adding new host to OAT server, following error message could be shown:
"Trust Agent failed with code '1007' and message 'Trust Agent: Error while creating identity.' [AS_TRUST_AGENT_ERROR] [1012]"

To resolve it, I used IP address as hostname. 
That is 
Host Name: Host's IP Address (not concerned about hostname command)
Host Ip Address: Host's IP Address

Anyway I could make a detour the problem, but it isn't like a primitive answer I think.

**Comment by ZahediAquino** [comment]
You mean you want to use the hostname and not the IP Address in the "Host Name :" field when adding a host?
If that's the question, then it seems like a DNS issue, you might want to modify your /etc/hosts file on your OAT Server, add the entry for your host. Should look something like this:

    192.168.1.83              yourhostname.com


Then you can use the hostname instead of the  IP in the "Host Name :" field. Normally when the hostname can't be resolved you get a different message though, it should be something like:

    "System error: yourhostnamegoeshere.com: Name or service not known [SYSTE_ERROR][1]"


I suggest you check both the tagent and catalina logs everytie you run into an issue, you might find information that can guide you to fix the problem and if  possible attach it so we can help you debug.

**Comment by mipsan** [comment]
I will try that, and talk to you soon!

**Comment by mipsan** [comment]
Zahedi, 

It is cleared. 
Exactly you're right!
Thanks.
